// File generated by Antigravity (Antigravity)
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can re-run any of the tenant-specific configurations to add support for a Windows desktop app.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can re-run any of the tenant-specific configurations to add support for a Linux desktop app.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAureG2Zfw_91wEe_KIV6xgBn3ciRHi3w',
    appId: '1:869626906416:web:9f00980a165fe77d40eaf5',
    messagingSenderId: '869626906416',
    projectId: 'biblical-word-scramble',
    authDomain: 'biblical-word-scramble.firebaseapp.com',
    storageBucket: 'biblical-word-scramble.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAureG2Zfw_91wEe_KIV6xgBn3ciRHi3w',
    appId: '1:869626906416:android:67ae16377317e1a340eaf5', // Inferred based on standard registration
    messagingSenderId: '869626906416',
    projectId: 'biblical-word-scramble',
    storageBucket: 'biblical-word-scramble.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAureG2Zfw_91wEe_KIV6xgBn3ciRHi3w',
    appId: '1:869626906416:ios:9a00980a165fe77d40eaf5', // Inferred
    messagingSenderId: '869626906416',
    projectId: 'biblical-word-scramble',
    storageBucket: 'biblical-word-scramble.firebasestorage.app',
    iosBundleId: 'com.example.biblicalWordScramble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAureG2Zfw_91wEe_KIV6xgBn3ciRHi3w',
    appId: '1:869626906416:ios:9a00980a165fe77d40eaf5', // Inferred
    messagingSenderId: '869626906416',
    projectId: 'biblical-word-scramble',
    storageBucket: 'biblical-word-scramble.firebasestorage.app',
    iosBundleId: 'com.example.biblicalWordScramble',
  );
}
